### PR TITLE
Feature/electricity load forecasting (PJM) tutorial using MLForecast 

### PR DESCRIPTION
**Pull request by uumami**
## Description

Notebook tutorial for  Forecasting Electricity Load using MLForcast. Includes comparison against Prophet, I excluded NeuralProphet since there were some incompatibility issues between libraries (causes problems in colab)
Checklist:
- [x ] This PR has a meaningful title and a clear description.
- [x ] The tests pass.
- [ x] All linting tasks pass.
- [x ] The notebooks are clean.

### CODE REVIEW

**Comment by uumami** [comment]
<p>Applied</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010201'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>Link fixed</p><p> </p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010227'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>removed unused libraries, modified to lowercase, added prophet to yamls</p><p> </p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010254'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010276'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010318'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010345'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>fixed</p><p> </p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010365'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010378'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>removed</p><p> </p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010407'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010426'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010443'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010473'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>Disabled and added comment for that snippet</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010493'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010507'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>removed</p><p> </p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010523'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>I improved the format, but I noticed that the indices returned by the fucntion evaluate returns a dataframe whete all the indiced are the same, this can case problems later. I checked if <code>metrics_comparison</code> that was received by the function had some issue with the indices, but it did not. Then i had to reset the index to improve the format <code>metrics_comparison.reset_index(drop=True).style.background_gradient(axis=0)</code></p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010547'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>I leave it like that to incentivice that type of naming, but added explanations for the functionality (different column names) when we use fit or crossvalidation</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010307'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
@jmoralez I implemented the changes

**Comment by jmoralez** [comment]
<p>It's still here</p><p> </p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010318'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jmoralez** [comment]
<p>the typo is still there "fast forecasting <strong>withclassical</strong> machine"</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010254'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010318'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>Is the same as one of the previous plots, but I think it looks nice to have it again there since in theory it is the transformations we are going to use in the rest of the notebook. It is a bit redundant, but it helps for fast reference. But i can remove it, I just like having it there as a visual queue</p><p> </p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1719746059'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1719746090'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1719746127'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1719746160'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by uumami** [comment]
@jmoralez I think is ready, I hope!

**Comment by jmoralez** [comment]
<p>it now says "withc lassical"</p><p> </p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1718010254'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jmoralez** [comment]
<p>Can you save it then? We try to avoid having any images saved in notebooks because they can produce diffs when running on a different machine due to the dimensions</p>

---

 <a href='https://app.reviewnb.com/Nixtla/mlforecast/pull/208/discussion/#comment-1719746059'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mergenthaler** [comment]
This is good work, lets try to merge it soon :)

**Review by jmoralez — APPROVED** [review]

**Pull request merged**
